### ISSUE TITLE
Documentation issue on page "https://github.com/gardener/bouquet/blob/master/README.md"

### ISSUE THREAD

**Issue by freegroup** [gardener-attic/bouquet#1]
emphasize a word in a MarkDown should be done with "*" or "**" instead of the single quote.
A single quote is for code and commands and some MarkDown rendered handle this in a special way. (e.g. adding copy to clipboard icon )

**You can support the new landing page of the gardener if you change this.**

![bildschirmfoto 2018-07-26 um 10 58 56](https://user-images.githubusercontent.com/1155039/43252516-fbdef0ba-90c2-11e8-907f-f2685e10bc4f.png)

---
Page: [https://github.com/gardener/bouquet/blob/master/README.md](https://github.com/gardener/bouquet/blob/master/README.md)
don't remove the link to the page. It's required for the processor

**Comment by freegroup** [comment]
note: the screenshot shows just an outlook if the document and the document contains much more issues with the *single quote*

**Comment by vlerenc** [comment]
Stale issue.
